### ISSUE TITLE
scientificNameAuthorship should not require braces

### ISSUE THREAD

**Issue by hyanwong** [GlobalNamesArchitecture/gn_crossmap#20]
At the moment, if I run the following input into crossmap -d 1, I get a 'canonical name exact match' rather than an 'exact match', because the author name isn't in braces.

```
taxonID,scientificNameAuthorship,scientificName
0,"Linnaeus, 1758",Abramis bjoerkna
```

So I have to do 

```
taxonID,scientificNameAuthorship,scientificName
0,"(Linnaeus, 1758)",Abramis bjoerkna
```

Can you remove the requirement for the braces in the scientificNameAuthorship field? It would be nice if this could also match against "L., 1758", and maybe even "L. 1758"

**Comment by dimus** [comment]
Exact match by definition means the exact match of a supplied string. Exact match by canonical name is often more useful and precise, because it adds semantic meaning to the search. In case of Abramis bjoerkna -- if this is a name from Systema naturae -- your version is correct, and CoL's parentheses are wrong. So it is perfectly correct that exact match by a string did not happen.

I probably should be more specific and instead of "Exact match" say "Exact string match" or something like that.

Matching by authors like Linn. Linnaeus, L. is happening on the score phase. All of them would be considered the same author by the match scoring.
