### ISSUE TITLE
bizarre matchedScore when adding a non-matching name

### ISSUE THREAD

**Issue by hyanwong** [GlobalNamesArchitecture/gn_crossmap#21]
Probably an issue for GNresolver in general, but matching the name "Acanthurus chirurgus" gives a sensible result, with 2 possible names of equal score (0.988):

> 1,Acanthurus chirurgus,Canonical form exact match,Acanthurus chirurgus,"Acanthurus chirurgus (Bloch, 1787)",Acanthurus chirurgus,species,species,,,0,0.988,26846886
> 1,Acanthurus chirurgus,Canonical form exact match,Acanthurus chirurgus,"Acanthurus chirurgus (non Bloch, 1787)",Acanthurus chirurgus,species,species,synonym,"Acanthurus bahianus Castelnau, 1855",0,0.988,26831504

whereas matching the same name but with scientificNameAuthorship = "(Linnaeus)" (which shouldn't match either hit), means that priority is given to the name that is a synonym (scores of 0.988 vs 0.75)

> 1,Acanthurus chirurgus,(Linnaeus),Canonical form exact match,Acanthurus chirurgus (Linnaeus),"Acanthurus chirurgus (non Bloch, 1787)",Acanthurus chirurgus,species,species,synonym,"Acanthurus bahianus Castelnau, 1855",0,0.988,26831504
> 1,Acanthurus chirurgus,(Linnaeus),Canonical form exact match,Acanthurus chirurgus (Linnaeus),"Acanthurus chirurgus (Bloch, 1787)",Acanthurus chirurgus,species,species,,,0,0.75,26846886
>

**Comment by dimus** [comment]
This particular scoring was generated in the following way:
1.  it was an exact match by canonical, which gave in both cases the score 0.988

2. Authorship was checked:
in the first case we matched `Linnaeus` vs `non Bloch`. `non Bloch` was ignored because it means almost any author (except Bloch). As a result score was not increased of decreased by comparison of authors and stayed 0.988.

in the second case `Linnaeus` vs `Bloch` was the authors mismatch, so the score went down
